name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Trigger Info
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: Build
    environment: test
    steps:
      - name: Run Tests
        run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: Build
    environment: load-test
    steps:
      - name: Run Load Tests
        run: |
          echo "🧪 Load Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: ${{ github.event.inputs.environment == 'Production' }}
    environment:
      name: production
      url: https://writeabout.net
    steps:
      - name: Production Deployment Step 1
        run: |
          echo "🚀 Step 1..."
          sleep 10
      - name: Production Deployment Step 2
        run: |
          echo "🚀 Step 2..."
          sleep 10
      - name: Production Deployment Step 3
        run: |
          echo "🚀 Step 3..."
          sleep 10
      - name: Production Deployment Step 4
        run: |
          echo "🚀 Step 4..."
          sleep 10
      - name: Production Deployment Step 5
        run: |
          echo "🚀 Step 5..."
          sleep 10
